# Generated by Django 5.2.1 on 2025-05-25 00:33

import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.CharField(
                default=shared.utils.generate_id,
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
