# Generated by Django 5.2.1 on 2025-05-17 15:02

import django.db.models.deletion
import shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shared.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type_dashboard",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=100,
                    ),
                ),
                ("insight", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shared.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("raw_data", models.JSONField(blank=True, null=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.dashboard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
