# Generated by Django 5.2.1 on 2025-05-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu_category", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menucategory",
            old_name="parent",
            new_name="parent_id",
        ),
    ]
