# Generated by Django 5.2.1 on 2025-05-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_category", "0002_rename_parent_menucategory_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menucategory",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
