# Generated by Django 5.2.1 on 2025-05-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="is_recommend",
            new_name="is_recommended",
        ),
    ]
