# Generated by Django 5.2.1 on 2025-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(default="Jane Doe", max_length=100),
        ),
    ]
