# Generated by Django 5.2.1 on 2025-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_customer_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=100),
        ),
    ]
